####################################################################################################
# DCS Units
# Weapons
weapon_gun = [
    "2A7_23_HE",
    "b-20",
    "GSH23_23_AP",
    "M56A3_HE_RED",
    "M61_20_AP",
    "M61_20_HE",
    "weapons.shells.2A28_73",
    "weapons.shells.2A42_30_AP",
    "weapons.shells.2A42_30_HE",
    "weapons.shells.2A46M_125_HE",
    "weapons.shells.2A60_120",
    "weapons.shells.2A7_23_AP",
    "weapons.shells.2A7_23_HE",
    "weapons.shells.5_45x39",
    "weapons.shells.7_62x51",
    "weapons.shells.GAU8_30_AP",
    "weapons.shells.GAU8_30_HE",
    "weapons.shells.GSH301_30_AP",
    "weapons.shells.KPVT_14_5_T",
    "weapons.shells.M242_25_AP_M919",
    "weapons.shells.M242_25_HE_M792",
    "weapons.shells.M256_120_AP",
    "weapons.shells.M256_120_HE",
    "weapons.shells.M2_12_7_T",
    "weapons.shells.M53_APT_RED",
    "weapons.shells.M56A3_HE_RED",
    "weapons.shells.M61_20_AP"
    "weapons.shells.M61_20_HE",
    "weapons.shells.M68_105_AP",
    "weapons.shells.UOF_412_100HE",
    "weapons.shells.Utes_12_7x108_T",
]

weapon_a2a = [
    "AIM-120B AMRAAM",
    "AIM-120C AMRAAM",
    "AIM-54A-MK",
    "AIM-54A-Mk60",
    "AIM-54C",
    "AIM-7 Sparrow",
    "AIM-7E Sparrow III",
    "AIM-7M Sparrow III",
    "AIM-9 Sidewinder",
    "AIM-9L Sidewinder"
    "AIM-9M Sidewinder",
    "AIM-9X Sidewinder",
    "MATRA",
    "MBDA",
    "R-27ER (AA-10 Alamo-C)",
    "R-27ET (AA-10 Alamo-D)",
    "R-27R (AA-10 Alamo-A)",
    "R-60 (AA-8 Aphid-A)",
    "R-60M (AA-8 Aphid-B)",
    "R-73 (AA-11 Archer)",
    "R-77 (AA-12 Adder)",
]

weapon_a2g = [
    "9K114 Shturm",
    "ADM_141A",
    "AGM-122 Sidearm",
    "AGM-65 Maverick",
    "AGM-65G Maverick",
    "AGM-88 HARM",
    "C_8",
    "CBU_97",
    "GBU_10",
    "GBU-12 Paveway II",
    "GBU_16",
    "KH-31A",
    "KONKURS",
    "MALUTKA",
    "Mark 84",
    "Mk-20 Rockeye",
    "Mk-82 Snake Eye",
    "RB75B",
    "RBK_250",
    "Vikhr_M",
    "X_25ML",
    "X_25MP",
    "X_31P",
    "X_58",
    "weapons.bombs.CBU_97",
    "weapons.bombs.CBU_97 Bomblets",
    "weapons.bombs.FAB_250",
    "weapons.bombs.GBU_16",
    "weapons.bombs.GBU_38",
    "weapons.bombs.RBK_250",
    "weapons.bombs.RBK_250 Bomblets",
    "weapons.missiles.KONKURS",
    "weapons.missiles.MALUTKA",
    "weapons.missiles.Vikhr_M",
]

weapon_g2a = [
    "3M9M",
    "5V27",
    "5V55R",
    "9M311",
    "9M33",
    "9M333",
    "9M38M1",
    "FIM_92C",
    "FIM_92C",
    "Igla_1E",
    "MIM-104",
    "MIM-23B",
    "RIM-66",
    "weapons.missiles.Igla_1E",
]

weapon_g2g = [
    "BGM_109B"
    "weapons.missiles.SVIR",
    "weapons.missiles.TOW2",
]

weapon_misc = [
    "Missile",
    "Rocket",
    "Bomb",
    "Pilot",
    "APU-170",
    "MER-5E",            # The MER-5E multiple ejector rack (MER)
    "weapons.nurs.C_8",
]

# Aircraft
aircrafts = [
    "A-10C Thunderbolt II",
    "A-50 Mainstay",
    "AJ 37 Viggen",
    "ALBATROS",
    "AV-8B Harrier II NA",
    "B-52H Stratofortress",
    "C-101CC",
    "C-17A Globemaster III",
    "E-2C",
    "E-3A Sentry",
    "F-14B Tomcat",
    "F-15C Eagle",
    "F-15E Strike Eagle",
    "F-4E Phantom II",
    "F-5E-3 Tiger II",
    "F/A-18C Hornet",
    "Il-78 Midas",
    "KC-130 Hercules",
    "KC-135 Stratotanker",
    "Ka-50 Black Shark",
    "L-39ZA Albatros",
    "Mi-8MT Hip",
    "Mi-24V Hind-E",
    "MiG-21bis Fishbed-L/N",
    "MiG-29A Fulcrum-A",
    "MiG-29S Fulcrum-C",
    "Mirage 2000C",
    "S-3B Viking",
    "SA 342L Gazelle",
    "SA 342M Gazelle",
    "Shenyang J-11A",
    "Su-24M Fencer-D",
    "Su-25 Frogfoot",
    "Su-25T Frogfoot",
    "Su-27 Flanker",
    "Su-30 Flanker-C",
    "Su-33 Flanker-D",
    "TF-51D Mustang",
    "Tu-142",
    "UH-1H Huey",
]

# Groundunits
groundunits = [
    "1L13 Nebo",
    "2B11 mortar",
    "AN/TWQ-1 Avenger",
    "ATMZ-5",
    "ATZ-10",
    "BMD-1",
    "BMP-1",
    "BMP-2",
    "BRDM-2",
    "BTR-0",
    "BTR-80",
    "BTR_D",
    "Bunker",
    "Boman",
    "CG-47 Ticonderoga",
    "Dog Ear Radar",
    "FARP",
    "FFG-7 Oliver Hazard Perry",
    "Fuel tank 300 gal",
    "GAZ-66",
    "HEMTT TFFT",
    "Igla manpad INS",
    "Infantry AK Ins",
    "Land_Rover_101_FC",
    "M 818",
    "M 818",
    "M-113",
    "M-2 Bradley",
    "M1 Abrams",
    "M113",
    "M163 Vulcan",
    "M6 Linebacker",
    "M978 HEMTT Tanker",
    "MIM-104 Patriot (AN/MPQ-53 STR)",
    "MIM-104 Patriot (M901 LN)",
    "MIM-23 Hawk (AN/MPQ-46 TR)",
    "MIM-23 Hawk (AN/MPQ-50 SR)",
    "MIM-23 Hawk (M192 LN)",
    "MIM-23 Hawk (M192 LN)",
    "MIM-23 Hawk (PCP CT)",
    "MOLNIYA",
    "MOSCOW",
    "NEUSTRASH",
    "Paratrooper AKS-74",
    "Paratrooper RPG-16",
    "SA-11 Gadfly (CC)",
    "SA-11 Gadfly (LN)",
    "SA-11 Gadfly (SR)",
    "SA-13 Gopher",
    "SA-18 Grouse",
    "SA-19 Grison",
    "SA-2 Guideline (Fan Song E TR)",
    "SA-3 Goa (LN)",
    "SA-3 Goa (SR)",
    "SA-3 Goa (TR Low Blow)",
    "SA-6 Gainful (LN)",
    "SA-6 Gainful (STR)",
    "SA-9 Gaskin",
    "SAU 2-C9",
    "SAU Akatsia",
    "SAU Msta",
    "S_75M_Volhov",
    "Silkworm_SR",
    "Soldier AK",
    "Soldier M249",
    "Soldier M4",
    "Soldier RPG",
    "Stinger manpad",
    "T-55",
    "T-72B",
    "UAZ-469",
    "Ural-375",
    "ZSU-23-4 Shilka",
    "ZU-23 Closed Insurgent",
    "ZU-23 Insurgent",
    "ZU-23-2 (Ural-375)",
    "ZU-23 Emplacement",
    "ZU-23-2",
    "house2arm",
    "hy_launcher"
    "55G6 Nebo",
]
